"""add_aquarium_parameter_thresholds

Revision ID: 20260726_000002
Revises: 20260726_000001
Create Date: 2026-07-26 21:16:50.017620
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260726_000002"
down_revision: Union[str, Sequence[str], None] = "20260726_000001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aquarium_parameter_thresholds",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("aquarium_id", sa.String(length=36), nullable=False),
        sa.Column("parameter", sa.String(length=32), nullable=False),
        sa.Column("target", sa.Float(), nullable=True),
        sa.Column("min", sa.Float(), nullable=True),
        sa.Column("max", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["aquarium_id"], ["aquariums.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "aquarium_id", "parameter", name="uq_aquarium_parameter_thresholds_aquarium_parameter"
        ),
    )
    op.create_index(
        op.f("ix_aquarium_parameter_thresholds_aquarium_id"),
        "aquarium_parameter_thresholds",
        ["aquarium_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aquarium_parameter_thresholds_parameter"),
        "aquarium_parameter_thresholds",
        ["parameter"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_aquarium_parameter_thresholds_parameter"),
        table_name="aquarium_parameter_thresholds",
    )
    op.drop_index(
        op.f("ix_aquarium_parameter_thresholds_aquarium_id"),
        table_name="aquarium_parameter_thresholds",
    )
    op.drop_table("aquarium_parameter_thresholds")
    # ### end Alembic commands ###
